### ISSUE TITLE
[Android] When will JSC be upgrade??

### ISSUE THREAD

**Issue by EruYan** [apache/incubator-weex#3153] opened 2020-02-21 04:10 UTC
JSC is still 2016 version, with low performance. 
Why not upgrade?

**Comment by ArrayDC** [comment] 2020-02-21 04:19
期待升级，官方还继续维护吗？

**Comment by xiaohuapunk** [comment] 2020-02-21 06:18
现在jsc的性能不太像，希望能升级一下

**Comment by cnryb** [comment] 2020-02-25 09:11
Duplicate of #3139

**Closed by cnryb** 2020-02-25 09:11 UTC
Labels: Bug

**Comment by cnryb** [comment] 2020-02-25 09:14
How did you determine that the JSC version was 2016 ？
