### ISSUE TITLE
[Android] Native Crash when starting app where weex version is unknown

### ISSUE THREAD

**Issue by williamthegrey** [apache/incubator-weex#2195] opened 2019-03-08 12:29 UTC
## Describe the bug

Native crash on Android when starting app

## To Reproduce

Reproduce by chance

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: '***********************************************************************'
Revision: '0'
ABI: 'arm'
pid: 5754, tid: 5767, name: libweexjsb.so  >>> /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjsb.so <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '/Volumes/Android/buildbot/src/android/ndk-r13-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type IPCException" failed'
    r0 00000000  r1 00001687  r2 00000006  r3 00000008
    r4 0000167a  r5 00001687  r6 f5c849fc  r7 0000010c
    r8 00000000  r9 f5204000  sl 7ffffffe  fp f5c84f00
    ip f5c84a44  sp f5c849e8  lr f6679933  pc f66737e4  cpsr 200a0030
    d0  0000000000000000  d1  00000000bf000000
    d2  00000000bde539fc  d3  0000000000000000
    d4  1248f64d0104f06f  d5  68a9f649724df6ce
    d6  f24046c62802f2cf  d7  0000000200000002
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 00000000006bca00  d17 00000000006a1848
    d18 fffffffffffffffb  d19 0000000001010001
    d20 4076700000000000  d21 0000000000000000
    d22 0000000000000000  d23 0000000000000000
    d24 b7b6b5b4b3b2b1b0  d25 bfbebdbcbbbab9b8
    d26 c7c6c5c4c3c2c1c0  d27 cfcecdcccbcac9c8
    d28 d7d6d5d4d3d2d1d0  d29 dfdedddcdbdad9d8
    d30 e7e6e5e4e3e2e1e0  d31 efeeedecebeae9e8
    scr 20000011

backtrace:
    #00 pc 0001a7e4  /system/lib/libc.so (abort+63)
    #01 pc 0001a9d3  /system/lib/libc.so (__assert2+22)
    #02 pc 00037609  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #03 pc 000376eb  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #04 pc 00035d0d  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #05 pc 000359b9  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #06 pc 004df2f9  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #07 pc 004de577  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #08 pc 004ddd7f  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #09 pc 004dde9b  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #10 pc 0002f201  /data/app/*****************************-2-yKl6M3xnv-YF0AcUGIrQ==/lib/arm/libweexjss.so
    #11 pc 00002a87  <anonymous:f1f02000>

## Environment

OS: Android 8.1

**Comment by YorkShen** [comment] 2019-03-11 02:36
Please update to the latest version of Weex, I think the problem is solved long time ago.

**Comment by YorkShen** [comment] 2019-03-26 07:27
As the problem is not update for weeks, I will just close it.

Feel free to reopen it if you have the problem in the latest version of Weex.

**Closed by YorkShen** 2019-03-26 07:27 UTC
Labels: Bug
