### ISSUE TITLE
Weex android debug is not work 

### ISSUE THREAD

**Issue by quanchaoguo** [apache/incubator-weex#1867] opened 2018-12-05 08:56 UTC
## Description
Weex debug is not work   with  weex app scan or  Android  simulator

weex app scan  alert  “devtool” 
Android simulator click QR code  alert  “模拟器调试暂时不可用” 

## Environment

weex -v
v1.3.11
 - weex-debugger : v1.2.5
 - weex-builder : v0.4.1
 - weex-previewer : v1.5.1

Project package.json
"weex-devtool": "0.3.8"

## Broken Example

<img width="588" alt="2018-12-05 4 52 18" src="https://user-images.githubusercontent.com/32917790/49501601-3b701800-f8ae-11e8-8d26-eaaa96ae35a1.png">

**Comment by erha19** [comment] 2018-12-06 04:03
@quanchaoguo the simulator debug has been closed, it will be active while `weex-toolkit@2.x` be published.

For now, you can use `weex playground app` to debug with your weex page, see [Weex Debug Document](http://weex.apache.org/tools/toolkit.html#debug).

**Comment by quanchaoguo** [comment] 2018-12-07 03:47
why phone is not work  I use phone scan alert " devtool "

**Comment by zkj881225** [comment] 2019-01-09 02:58
![image](https://user-images.githubusercontent.com/33045988/50874005-4b26d300-13fd-11e9-9e2d-63a7fe89d54d.png)

why i use weex playground app scan it,show this?

this is weex playground app's page,not my app

**Comment by erha19** [comment] 2019-01-09 03:31
@zkj881225 that's ok, while the JSDebug is not open, the devtool will show you the native log print by devtool SDK, you can use the filter on the top menu to see what you want to see.

**Comment by zkj881225** [comment] 2019-01-09 08:13
老哥，要不您用中文帮我解释下，英文看得懂，但是理解起来可能有偏差。

**Comment by zkj881225** [comment] 2019-01-09 09:19
now i input command: weex debug src/views/home/Home.vue

![image](https://user-images.githubusercontent.com/33045988/50889232-77a91200-1432-11e9-9f98-bf7ebeff8b07.png)

it like right,but i can't debug my app.


i want to use:weex-devtool，debug the project ,not one page.

**Comment by zkj881225** [comment] 2019-01-10 07:49
![image](https://user-images.githubusercontent.com/33045988/50953685-201cac00-14ef-11e9-8ecb-9aadde599e9e.png)
官方文档不是说运行weex debug,用weex playground app扫描后会出现设备列表吗？根本没看到啊。

安装了weex-devtool命令有没用，出现的是这个页面，求大佬帮忙

![image](https://user-images.githubusercontent.com/33045988/50953754-51957780-14ef-11e9-8cec-36a20c8fd7b8.png)

**Comment by zkj881225** [comment] 2019-01-11 01:37
我解决了问题，把nodejs安装成8版本的，就可以了

**Comment by quanchaoguo** [comment] 2019-01-11 01:38
劝你不要用weex 真的坑

**Comment by quanchaoguo** [comment] 2019-01-11 01:39
我用快一年了  真心不好用 生态差到没朋友

**Comment by YorkShen** [comment] 2019-01-11 08:44
> 我用快一年了 真心不好用 生态差到没朋友

I will close this as the problem is solved

BTW, contribution is welcomed,  insulting or derogatory comments is unacceptable according to weex community [code of conduct](https://github.com/apache/incubator-weex/blob/master/CODE_OF_CONDUCT.md).

Be the change you want to in the world, thanks.

**Closed by YorkShen** 2019-01-11 08:44 UTC
Labels: Tools

**Comment by zkj881225** [comment] 2019-01-14 07:33
凑合着用吧，比写原生快。另外我发现改为8版本的Node之后，启动会生成applist页面，但是调试不了
#2041
