### ISSUE TITLE
[iOS][WeexSDK] iconfont can not showed as expected where weex version is 0.26.0

### ISSUE THREAD

**Issue by amiacoder** [apache/incubator-weex#3034] opened 2019-11-25 05:49 UTC
Loading two iconfont ttf files at the same time, the fonts in one font library are not displayed, and are normal on the browser.

this is the test dotwe address
http://dotwe.org/vue/f378cb6fecaff54b6951326e4a2002a2

Environment
Device: [e.g. iPhone X]
OS: [e.g. iOS13.1]
Version [e.g. 0.26.0]
Build from source [e.g. yes]

![68844635-106c8600-0705-11ea-8244-5b18971973d6](https://user-images.githubusercontent.com/5467305/69515696-5c7fbc00-0f8a-11ea-98c7-ae9d9a858a27.png)
![68844722-342fcc00-0705-11ea-9571-b43873748f22](https://user-images.githubusercontent.com/5467305/69515703-630e3380-0f8a-11ea-86fb-9de3c78392a9.png)

**Comment by YorkShen** [comment] 2019-11-25 07:45
@jianhan-he Have a look ?

**Comment by YorkShen** [comment] 2019-11-25 07:45
The issue is very similar with https://github.com/apache/incubator-weex/issues/3014

**Comment by amiacoder** [comment] 2019-11-26 02:05
> The issue is very similar with #3014

Yes, They were both posted by me. Please help me to resolve this problem, thx

**Comment by YorkShen** [comment] 2019-11-27 03:23
Close this issue as it solved in https://github.com/apache/incubator-weex/issues/3014#issuecomment-558519447

**Closed by YorkShen** 2019-11-27 03:23 UTC
Labels: Bug
