### ISSUE TITLE
[Android] Unexpected behavior when build from source where weex version is 0.28.0

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#3103] opened 2020-01-03 09:57 UTC
i try to build a weex sdk with armeabi so directory.
`./gradlew assembleRelease --quiet -PbuildRuntimeApi=true -PsupportArmeabi-v7a=true -PsupportArmeabi=true  -PsupportArm64-v8a=false -PsupportX86=false -PapachePackageName="false" -PremoveSharedLib=true`

but the aar file contains no armeabi directory under jni directory.

**Comment by zsmjhtn** [comment] 2020-01-06 02:23
Please don't use armeabi anymore, Google stopped supporting it years ago.

Weex only supports armeabi-v7a, arm64-v8a and x86 and we don't test Weex on armeabi anymore.
Duplicate of #3013

**Closed** 2020-01-07 14:33 UTC
Labels: Bug
